name: test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry # disable to speed up
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      # - name: Install Dependencies
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install lcov genhtml


      - name: Parse and Check Coverage
        run: |
          forge coverage --report lcov
          coverage=$(lcov --summary lcov.info | grep "lines\.*:" | awk '{print $2}' | sed 's/%//')
          echo "Coverage is $coverage%"
          if (( $(echo "$coverage < 60.0" | bc -l) )); then
            echo "Test coverage is below 60%"
            exit 1
          fi
        id: check-coverage

      - name: Run Forge build # disable for faster
        run: |
          forge --version
          forge build --sizes
        id: build

      # - name: Run Forge tests # disable to faster
      #   run: |
      #     forge test -vvv
      #   id: test

      - name: Run Echidna
        uses: crytic/echidna-action@v2
        with:
          files: src/Counter.sol
          contract: Counter
          crytic-args: --ignore-compile
